(function () {
'use strict';
if (!globalThis.UrlPurifier || !globalThis.UrlPurifierI18n) {
  console.error('URL Purifier dependencies did not load.');
  document.getElementById('resultsContainer')?.replaceChildren(Object.assign(document.createElement('p'), { className: 'empty-state', textContent: '应用依赖未能加载，请刷新页面或检查 src/js/purifier.js。' }));
  return;
}
const { extractAndPurifyUrls, redactCredentials } = globalThis.UrlPurifier;
const dictionaries = globalThis.UrlPurifierI18n;
const MAX_HISTORY = 20, STORAGE_KEY = 'url_purifier_history', THEME_KEY = 'url_purifier_theme', LANGUAGE_KEY = 'url_purifier_language';
const safeStorage = Object.freeze({ get: (key) => { try { return localStorage.getItem(key); } catch { return null; } }, set: (key, value) => { try { localStorage.setItem(key, value); return true; } catch { return false; } } });
let currentResults = [], historyData = [], toastTimer, modalReturnFocus, currentLanguage = safeStorage.get(LANGUAGE_KEY) === 'en' ? 'en' : 'zh-CN';
const $ = (id) => document.getElementById(id); const inputText = $('inputText'), charCount = $('charCount'), purifyBtn = $('purifyBtn'), resultsContainer = $('resultsContainer'), historyContainer = $('historyContainer'), toast = $('toast'), modalOverlay = $('modalOverlay'), modal = $('modal'), modalTitle = $('modalTitle'), modalBody = $('modalBody'), modalFooter = $('modalFooter'), themeToggle = $('themeToggle'), languageToggle = $('languageToggle');
function t(key, params = {}) { return (dictionaries[currentLanguage][key] || dictionaries['zh-CN'][key] || key).replace(/\{(\w+)\}/gu, (_, name) => String(params[name] ?? '')); }
function el(tag, options = {}, children = []) { const node = document.createElement(tag); Object.entries(options).forEach(([key, value]) => { if (key === 'text') node.textContent = value; else if (key === 'className') node.className = value; else if (key === 'dataset') Object.assign(node.dataset, value); else node.setAttribute(key, value); }); node.append(...children.filter(Boolean)); return node; }
function button(key, action, payload = '', className = 'btn btn-secondary btn-sm') { return el('button', { type: 'button', className, text: t(key), dataset: { action, payload: String(payload) } }); }
function setTheme(dark) { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; themeToggle.setAttribute('aria-label', t(dark ? 'themeLight' : 'themeDark')); themeToggle.title = themeToggle.getAttribute('aria-label'); $('moonIcon').hidden = dark; $('sunIcon').hidden = !dark; themeToggle.classList.remove('is-switching'); void themeToggle.offsetWidth; themeToggle.classList.add('is-switching'); safeStorage.set(THEME_KEY, dark ? 'dark' : 'light'); }
function link(url, className = 'result-url', label = url) { return el('a', { href: url, target: '_blank', rel: 'noopener noreferrer', className, text: label }); }
function formatTime(timestamp) { return new Date(timestamp).toLocaleString(currentLanguage === 'en' ? 'en-US' : 'zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); }
function showToast(message, type = 'info') { clearTimeout(toastTimer); toast.textContent = message; toast.dataset.type = type; toast.classList.add('show'); toastTimer = setTimeout(() => toast.classList.remove('show'), 2200); }
function switchTab(name, focus = false) { ['results', 'history'].forEach((tab) => { const selected = tab === name, upper = `${tab[0].toUpperCase()}${tab.slice(1)}`, btn = $(`tab${upper}`), panel = $(`content${upper}`); btn.classList.toggle('active', selected); btn.setAttribute('aria-selected', String(selected)); btn.tabIndex = selected ? 0 : -1; panel.classList.toggle('active', selected); panel.hidden = !selected; if (selected && focus) btn.focus(); }); if (name === 'history') renderHistory(); }
function empty(title, detail = '') { const node = el('div', { className: 'empty-state' }, [el('p', { text: title }), detail && el('p', { className: 'empty-state-detail', text: detail })]); return node; }
function renderResults(results = currentResults) { resultsContainer.replaceChildren(); if (!results.length) { resultsContainer.append(empty(t('noUrls'), t('noUrlsHint'))); return; } const list = el('div', { className: 'result-list' }); results.forEach((result) => { const status = !result.changed ? t('valid') : result.confidence === 'medium' || result.confidence === 'low' ? t('review') : t('cleaned'); const card = el('article', { className: 'result-card' }); card.append(el('p', { className: 'result-label', text: t('original') }), el('p', { className: 'result-original', text: result.hasCredentials ? redactCredentials(result.original) : result.original }), el('p', { className: 'result-label', text: t('purified') }), link(result.purified), el('p', { className: `result-status ${result.warning ? 'has-warning' : ''}`, text: `${status}${result.changed ? ` · ${t('modified', { count: result.changeCount })}` : ''}` })); if (result.warning) card.append(el('p', { className: 'result-warning', text: result.hasCredentials ? t('credentials') : t('review') })); card.append(el('div', { className: 'result-actions' }, [button('copy', 'copy', result.purified), button('visit', 'visit', result.purified)])); list.append(card); }); resultsContainer.append(list, button('copyAll', 'copy-all', results.map((r) => r.purified).join('\n'), 'btn btn-secondary')); }
function validEntry(entry) { return entry && typeof entry.id === 'string' && Number.isFinite(entry.timestamp) && Array.isArray(entry.results); }
function loadHistory() { try { const saved = JSON.parse(safeStorage.get(STORAGE_KEY) || '[]'); historyData = Array.isArray(saved) ? saved.map((entry) => validEntry(entry) ? entry : entry && Array.isArray(entry.urls) && Number.isFinite(entry.timestamp) ? { id: String(entry.id || entry.timestamp), timestamp: entry.timestamp, results: entry.urls.map((purified) => ({ original: purified, purified, changed: false, changeCount: 0, warning: '', confidence: 'high', hasCredentials: false })) } : null).filter(Boolean).slice(0, MAX_HISTORY) : []; } catch { historyData = []; } renderHistory(); }
function saveHistory() { safeStorage.set(STORAGE_KEY, JSON.stringify(historyData)); }
function addHistory(results) { historyData.unshift({ id: `${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`, timestamp: Date.now(), results: results.map((r) => r.hasCredentials ? { ...r, original: redactCredentials(r.original), purified: redactCredentials(r.purified) } : r) }); historyData = historyData.slice(0, MAX_HISTORY); saveHistory(); renderHistory(); }
function renderHistory() { historyContainer.replaceChildren(); if (!historyData.length) { historyContainer.append(empty(t('historyEmpty'))); return; } const list = el('div', { className: 'history-list' }); historyData.forEach((entry) => { const urls = el('div', { className: 'history-urls' }); entry.results.forEach((r) => urls.append(link(r.purified, 'history-url-link'))); const card = el('article', { className: 'history-item' }, [el('div', { className: 'history-header' }, [el('span', { className: 'history-time', text: formatTime(entry.timestamp) }), el('span', { className: 'history-count', text: t('historyCount', { count: entry.results.length }) })]), urls, el('div', { className: 'history-actions' }, [button('detail', 'history-detail', entry.id), button('delete', 'history-delete', entry.id)])]); list.append(card); }); historyContainer.append(list, button('clearHistory', 'history-clear', '', 'btn btn-secondary')); }
function setModal(title, body, actions, trigger) { modalReturnFocus = trigger || document.activeElement; modalTitle.textContent = title; modalBody.replaceChildren(...body); modalFooter.replaceChildren(...actions); modalOverlay.classList.add('active'); document.body.classList.add('modal-open'); requestAnimationFrame(() => modal.querySelector('button, a')?.focus()); }
function closeModal() { if (!modalOverlay.classList.contains('active')) return; modalOverlay.classList.remove('active'); document.body.classList.remove('modal-open'); modalReturnFocus?.focus?.(); }
function details(id, trigger) { const entry = historyData.find((item) => item.id === id); if (!entry) return; const urls = el('div', { className: 'modal-text' }); entry.results.forEach((r) => urls.append(link(r.purified, 'history-url-link'))); setModal(t('detail'), [el('p', { className: 'modal-section-label', text: t('time', { time: formatTime(entry.timestamp) }) }), urls], [button('close', 'modal-close'), button('copyAllUrls', 'copy-all', entry.results.map((r) => r.purified).join('\n'), 'btn btn-primary')], trigger); }
function info(type, trigger) { const key = type === 'help' ? 'helpText' : type === 'faq' ? 'faqText' : 'aboutText'; setModal(t(type), [el('p', { className: 'modal-text', text: t(key) })], [button('close', 'modal-close')], trigger); }
async function copy(value) { try { await navigator.clipboard.writeText(value); } catch { const area = el('textarea', { 'aria-hidden': 'true' }); area.value = value; document.body.append(area); area.select(); const ok = document.execCommand('copy'); area.remove(); if (!ok) throw new Error('copy'); } showToast(t('copySuccess'), 'success'); }
function purify() { if (!inputText.value.trim()) { showToast(t('inputRequired'), 'warning'); return; } purifyBtn.disabled = true; try { currentResults = extractAndPurifyUrls(inputText.value); renderResults(); if (currentResults.length) { addHistory(currentResults); showToast(t('processed', { count: currentResults.length }), 'success'); } else showToast(t('noUrls'), 'warning'); switchTab('results'); } catch (error) { console.error(error); currentResults = []; renderResults(); switchTab('results'); showToast(t('processFailed'), 'error'); } finally { purifyBtn.disabled = false; } }
function updateInputState() { charCount.textContent = t('characterCount', { count: inputText.value.length }); $('clearInputBtn').hidden = !inputText.value.length; }
function applyLanguage() { document.documentElement.lang = currentLanguage; document.title = t('title'); document.querySelectorAll('[data-i18n]').forEach((node) => { const key = node.dataset.i18n; if (node.dataset.i18nAttr) node.setAttribute(node.dataset.i18nAttr, t(key)); else node.textContent = t(key); }); updateInputState(); languageToggle.setAttribute('aria-label', t('language')); languageToggle.title = t('language'); renderResults(currentResults); renderHistory(); if (modalOverlay.classList.contains('active')) closeModal(); }
document.addEventListener('click', (event) => { const target = event.target.closest('[data-action]'); if (!target) return; const { action, payload } = target.dataset; if (action === 'copy' || action === 'copy-all') copy(payload).catch(() => showToast(t('copyFailed'), 'error')); else if (action === 'visit') window.open(payload, '_blank', 'noopener,noreferrer'); else if (action === 'history-detail') details(payload, target); else if (action === 'history-delete') { historyData = historyData.filter((item) => item.id !== payload); saveHistory(); renderHistory(); showToast(t('deleted'), 'success'); } else if (action === 'history-clear') setModal(t('confirmClear'), [el('p', { className: 'modal-text', text: t('confirmClearText') })], [button('cancel', 'modal-close'), button('confirm', 'history-clear-confirm', '', 'btn btn-primary')], target); else if (action === 'history-clear-confirm') { historyData = []; saveHistory(); renderHistory(); switchTab('history'); closeModal(); showToast(t('cleared'), 'success'); } else if (action === 'modal-close') closeModal(); else if (action.startsWith('help-')) info(action.slice(5), target); });
purifyBtn.addEventListener('click', purify); $('clearInputBtn').addEventListener('click', () => { inputText.value = ''; updateInputState(); inputText.focus(); }); themeToggle.addEventListener('click', () => setTheme(document.documentElement.dataset.theme !== 'dark')); languageToggle.addEventListener('click', () => { currentLanguage = currentLanguage === 'zh-CN' ? 'en' : 'zh-CN'; safeStorage.set(LANGUAGE_KEY, currentLanguage); applyLanguage(); }); inputText.addEventListener('input', updateInputState); inputText.addEventListener('keydown', (e) => { if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); purify(); } }); document.querySelector('.tabs').addEventListener('click', (e) => { const tab = e.target.closest('[role="tab"]'); if (tab) switchTab(tab.dataset.tab); }); document.querySelector('.tabs').addEventListener('keydown', (e) => { const names = ['results', 'history']; const index = names.findIndex((name) => $(`tab${name[0].toUpperCase()}${name.slice(1)}`) === document.activeElement); if (index < 0) return; const next = e.key === 'Home' ? 0 : e.key === 'End' ? 1 : ['ArrowLeft', 'ArrowRight'].includes(e.key) ? (index + 1) % 2 : null; if (next !== null) { e.preventDefault(); switchTab(names[next], true); } }); modalOverlay.addEventListener('click', (e) => { if (e.target === modalOverlay) closeModal(); }); document.addEventListener('keydown', (e) => { if (!modalOverlay.classList.contains('active')) return; if (e.key === 'Escape') closeModal(); });
setTheme(safeStorage.get(THEME_KEY) === 'dark'); loadHistory(); applyLanguage(); switchTab('history');
})();
