(function (global) {
'use strict';
const zh = {
  title: '网址净化工具 - URL Purifier', brand: '网址净化工具', inputLabel: '需要净化的文本', inputKicker: '输入', inputTitle: '粘贴污染文本', characterCount: '已输入 {count} 字符', placeholder: '例如：https://exa😊mple.com/path\n或者：复制这段文字 https://exa mple.com 到浏览器打开', purify: '一键净化', clearInput: '清空输入', shortcut: '⌘ / Ctrl + Enter 快速净化', results: '净化结果', history: '历史记录', tabLabel: '输出内容', resultsEmpty: '净化后的网址会显示在这里', noUrls: '未检测到有效网址', noUrlsHint: '请确认内容中包含完整的 http:// 或 https:// 地址', historyEmpty: '暂无历史记录，快去净化第一个网址吧', tip1: '支持一次粘贴多段文本，自动识别其中的多个网址。', tip2: '网址净化在浏览器中完成，输入内容不会上传。', tip3: '按 ⌘ / Ctrl + Enter 可以快速净化当前输入内容。', footer: '网址内容仅在浏览器中处理', help: '使用说明', faq: '常见问题', about: '关于', original: '原始候选 URL', purified: '净化后的 URL', valid: '网址本身已有效', cleaned: '已清理污染字符', review: '建议结果，请核对后访问', modified: '已修改约 {count} 个字符', credentials: '链接含有账号或密码；历史记录会隐藏凭据。', copy: '复制', copyAll: '复制全部结果', copyAllUrls: '复制全部 URL', visit: '访问', detail: '查看详情', delete: '删除', clearHistory: '清空全部历史记录', historyCount: '{count} 个 URL', processed: '已处理 {count} 个网址', inputRequired: '请先粘贴包含网址的文本', copySuccess: '已复制到剪贴板', copyFailed: '复制失败，请手动复制', deleted: '已删除记录', cleared: '历史记录已清空', processFailed: '处理失败，请检查输入内容', confirmClear: '确认清空', confirmClearText: '确定要清空所有历史记录吗？此操作不可恢复。', cancel: '取消', confirm: '确认清空', close: '关闭', time: '处理时间：{time}', helpText: '粘贴包含完整 http:// 或 https:// 地址的文本，点击净化后可复制或主动访问结果。', faqText: '处理完全在浏览器本地完成。严重污染的网址属于启发式结果，访问前请人工核对。', aboutText: '网址净化工具使用原生 HTML、CSS 与 JavaScript 实现。URL 处理在浏览器中完成，页面使用 Google Fonts 提供在线字体。', themeDark: '切换到深色模式', themeLight: '切换到浅色模式', language: '切换到 English', dependencyError: '应用依赖未能加载，请刷新页面或检查 src/js/purifier.js。'
};
const en = {
  title: 'URL Purifier', brand: 'URL Purifier', inputLabel: 'Text to purify', inputKicker: 'Input', inputTitle: 'Paste polluted text', characterCount: '{count} characters entered', placeholder: 'Example: https://exa😊mple.com/path\nOr paste text containing https://exa mple.com', purify: 'Purify URLs', clearInput: 'Clear input', shortcut: '⌘ / Ctrl + Enter to purify', results: 'Results', history: 'History', tabLabel: 'Output content', resultsEmpty: 'Purified URLs will appear here', noUrls: 'No valid URLs detected', noUrlsHint: 'Make sure the text includes a complete http:// or https:// URL', historyEmpty: 'No history yet. Purify your first URL to get started.', tip1: 'Paste multiple passages and detect URLs in one go.', tip2: 'URL purification runs in your browser. Your input is not uploaded.', tip3: 'Press ⌘ / Ctrl + Enter to purify the current input.', footer: 'URL content is processed in your browser', help: 'How to use', faq: 'FAQ', about: 'About', original: 'Original URL candidate', purified: 'Purified URL', valid: 'The URL is already valid', cleaned: 'Polluting characters removed', review: 'Suggested result — review before visiting', modified: 'About {count} characters changed', credentials: 'This URL contains credentials; history hides them.', copy: 'Copy', copyAll: 'Copy all results', copyAllUrls: 'Copy all URLs', visit: 'Visit', detail: 'View details', delete: 'Delete', clearHistory: 'Clear all history', historyCount: '{count} URL(s)', processed: '{count} URL(s) processed', inputRequired: 'Paste text containing a URL first', copySuccess: 'Copied to clipboard', copyFailed: 'Copy failed. Please copy manually.', deleted: 'Record deleted', cleared: 'History cleared', processFailed: 'Processing failed. Check the input and try again.', confirmClear: 'Clear history?', confirmClearText: 'Clear all history? This cannot be undone.', cancel: 'Cancel', confirm: 'Clear history', close: 'Close', time: 'Processed: {time}', helpText: 'Paste text that includes a complete http:// or https:// URL, then purify it to copy or deliberately visit the result.', faqText: 'Processing happens in your browser. Heavily polluted URLs are heuristic results; review them before visiting.', aboutText: 'URL Purifier is built with native HTML, CSS, and JavaScript. URL processing runs in your browser, while Google Fonts is used for web typography.', themeDark: 'Switch to dark mode', themeLight: 'Switch to light mode', language: '切换到中文', dependencyError: 'Application dependencies did not load. Refresh the page or check src/js/purifier.js.'
};
global.UrlPurifierI18n = Object.freeze({ 'zh-CN': Object.freeze(zh), en: Object.freeze(en) });
})(globalThis);
